version: "3.9"
services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_Passw0rd!
    ports: ["1433:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P 'Your_strong_Passw0rd!' -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 20

  app:
    environment:
      - DB_SERVER=sql,1433
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: ../.env
    depends_on:
      sql:
        condition: service_healthy
